name: AdminBans
version: ${project.version}
main: com.rabbitcompany.adminbans.AdminBans
api-version: 1.13
load: STARTUP
authors: [CrazyRabbit]
description: Manage bans, warns, kicks and mutes.
website: https://rabbit-company.com
softdepend: [PlaceholderAPI]
commands:
  adminbans:
    usage: /<command>
    aliases: [abans, ab]
    description: Show settings
  ban:
    usage: /<command>
    description: Ban player
  banip:
    usage: /<command>
    description: Ban ip
  ban-ip:
    usage: /<command>
    description: Ban ip
  unban:
    usage: /<command>
    description: Unban player
  unbanip:
    usage: /<command>
    description: Unban ip
  kick:
    usage: /<command>
    description: Kick player
  warn:
    usage: /<command>
    description: Warn player
  mute:
    usage: /<command>
    description: Mute player
  unmute:
    usage: /<command>
    description: Unmute player
  banlist:
    usage: /<command>
    description: Show all banned players
  mutelist:
    usage: /<command>
    description: Show all muted players
